### ISSUE TITLE
enhancement - Sample Project

### ISSUE THREAD

**Issue by Sun3** [IainMcManus/iOSCoreLibrary#1]
I would like to suggest an enhancement to add a Sample Project to show how the library works and is implemented. I know it is well documented but looking at sample code always helps a lot.

Thank you for considering it and for the great library.

**Comment by IainMcManus** [comment]
I'm hoping to add a complete sample project in the next couple of weeks :)

**Comment by Sun3** [comment]
Thanks a lot... one of my biggest worries is to convert to iCloud current users that have iPhone and iPad data that are not synced :)

**Comment by IainMcManus** [comment]
I have added a basic (but working) sample app which shows how to use the iCloud + Core Data stack component of the library. Specifically it includes:
- Initial setup (import of existing data)
- Responding to external changes
- Removing duplicate data

I'll progressively update it to include some more complicated object setups and show more of the library.

**Comment by Sun3** [comment]
Great, I will check it out. Have you run into any issues where the first time you migrate current local core data to iCloud with the self.persistentStoreCoordinator migratePersistentStore... and the migration crashes because certain children records do not have a parent record? At least this is what I think the error is pointing to.

```
// iCloud
- (void)migrateStoreShared {

    // grab the current store
    NSPersistentStore *currentStore = persistentStoreCoordinator_.persistentStores.lastObject;

    // create a new URL
    NSURL *newStoreURL = [NSURL fileURLWithPath:[[self applicationDocumentsDirectory] stringByAppendingPathComponent: @"Database-iCloud.sqlite"]];

    // setup new options dictionary if necessary
    NSDictionary *options =
    @{
      NSMigratePersistentStoresAutomaticallyOption:@YES
      ,NSInferMappingModelAutomaticallyOption:@YES
      ,NSPersistentStoreUbiquitousContentNameKey:@"Database-iCloud"
      //,NSPersistentStoreUbiquitousContentURLKey:@"ChangeLogs" // Optional since iOS7
      };

    // migrate current store to new URL
    NSError *error;
    NSPersistentStore *iCloudStore = [persistentStoreCoordinator_ migratePersistentStore:currentStore toURL:newStoreURL options:options withType:NSSQLiteStoreType error:&error];
    NSLog(@"DONE Migrating? %@", [iCloudStore URL]);
}

Error:
Error: Error Domain=NSCocoaErrorDomain Code=133000 “The operation couldn’t be completed. (Cocoa error 133000.)” UserInfo=0x1126e4b0 {NSUnderlyingException=Referential integrity problem found during migratePersistentStore:toURL:options:withType:error: CoreData could not fulfill a fault for ’0×11279970 ‘}
```

Thanks.

**Comment by IainMcManus** [comment]
I have seen that exact error before in one of my more complex apps. At the time I identified two things which were causing the corrupted data:
- Crashes caused by bugs during the database save
- Accessing the same managed object context from multiple threads (reading or writing)

After fixing those I never saw any more corrupted data. For my use case all of the corrupted data appeared to be duplicates and I was able to safely eliminate them. For my case the layout of my models permitted me to safely delete any child objects without a link to a parent.

**Comment by Sun3** [comment]
Thanks for the tips. In my case I only receive this error when trying to convert the first time local core data to iCloud by using '''migratePersistentStore'''   

At this point I am going to try to remove child objects that have missing parents to see if that works. What worried me was also might happen when trying to convert users DB's in the wild :)

Since I have so many tables it is going to be a big job. Do you have any suggestions on generic logic to look for lost child objects without parents or each table will need to be custom code?

Thank you again.

**Comment by IainMcManus** [comment]
I'm not aware of any generic method for detecting corruption in the form of lost objects. It's very specific to the data model. A missing parent may be invalid for one app but perfectly valid for another.

**Comment by Sun3** [comment]
Yea, I hear you. In my app it is ok to have some of the child records without parent but for some reason iCloud is complaining. Unless I am misunderstanding the error that it gives during conversation. I will update with a status on what I did once I get the error handled.

Thanks... really do love your iCloud classes.

**Comment by IainMcManus** [comment]
Sample project added.
